"""
Portfolio optimization with covariance-based risk modeling and 
iterative factor-concentration filtering.

Pipeline:
1. Load daily returns from returns.csv
2. Compute covariance matrix, factor analysis (correlations + betas to ETFs)
3. Historical-mean expected returns
4. Sharpe-maximization optimizer (baseline)
5. Iterative risk filter that detects multi-stock factor concentration
   and applies dynamic group-weight caps via constraint generation
6. Multi-window out-of-sample backtest comparing filtered vs unfiltered vs benchmarks

Usage: python calc.py
Requires: returns.csv in the working directory (generated by download.py)
"""


import pandas as pd 
import numpy as np 
from scipy.optimize import minimize

stocks = ['AAPL', 'NVDA', 'MSFT', 'GOOGL', 'META', 'AMZN', 'TSLA', 'AMD', 'JPM', 'KO']
etfs = ['SPY', 'XLK', 'XLF', 'XLV', 'XLE', 'XLY', 'IWM']
rf = 0.045

# use dates as index and then turn dates into date_time objects
data = pd.read_csv("returns.csv", index_col=0, parse_dates = True)
stock_data = data[stocks]
etf_data = data[etfs]

stock_num = len(stocks)
initial_weights = np.array([1/stock_num] * stock_num)


# gen cov matrix function
def gen_cov_stocks(x):
    cov_matrix = np.cov(x, rowvar=False) * 252
    return cov_matrix


# gen Factor Analysis correlations between each stock and each etf --> keep for hidden concentration risk, will be utilized later
def factor_analysis_corr (returns_data):
    # new corr grid
    corr_grid = pd.DataFrame(index = stocks, columns= etfs, dtype=float)
    for stock in stocks:
        for etf in etfs:
            corr_grid.loc[stock, etf] = returns_data[stock].corr(returns_data[etf])
    return corr_grid

# Factor Analysis Beta values between each stock and each etf
def factor_analysis_beta(returns_data):
    beta_grid = pd.DataFrame(index=stocks, columns=etfs, dtype=float)
    for stock in stocks:
        for etf in etfs:
            cov = returns_data[stock].cov(returns_data[etf])
            var = returns_data[etf].var()
            beta_grid.loc[stock, etf] = cov / var
    return beta_grid

ß
# get expected return values --> using historical mean annual returns
def get_hist_returns(returns_data):
    expected_return = returns_data[stocks].mean() * 252
    return expected_return


# calculate the sharpe ratio, and return it as negative for scipy minimization (cannot max)
def calc_sharpe_ratio(weights, covariance_matrix, expected_returns, rf_rate):
    portfolio_return = np.dot(expected_returns, weights)
    portfolio_std = np.sqrt(np.dot(np.dot(weights, covariance_matrix), weights))
    sharpe = (portfolio_return - rf_rate) / portfolio_std
    return 0 - sharpe


# Multivariate Risk Filter --> stocks have high corr with each other, both share same dominant ETF, high ETF corr. --> caps at 40% total combined portfolio weight
def multi_risk_filter(corr_grid, corr_matrix, optimal_weights):

    flagged_pairs = []
    stock_etf_corr_thresh = 0.70
    combined_weight_thresh = 0.40
    inter_stock_corr_thresh = 0.60

    for etf in corr_grid.columns:
        problems_series = corr_grid[etf] >= stock_etf_corr_thresh
        strong_corr_stocks = corr_grid.index[problems_series].to_list()
        
        if not strong_corr_stocks:
            continue 
        
        if len(strong_corr_stocks) < 2:
            continue
            
        # check corr between each other 
        sub_corr = corr_matrix.loc[strong_corr_stocks, strong_corr_stocks]
        confirmed_stocks = []
        
        for stock in sub_corr.columns:
            problem_stocks = sub_corr[stock] >= inter_stock_corr_thresh
            within_stock_str_corr_stocks = sub_corr.index[problem_stocks].to_list()

            if stock in within_stock_str_corr_stocks:
                within_stock_str_corr_stocks.remove(stock)
            
            if len(within_stock_str_corr_stocks) >= 1:
                confirmed_stocks.append(stock)
        
        confirmed_weight = optimal_weights[confirmed_stocks].sum()
        if confirmed_weight > combined_weight_thresh:
            flagged_pairs.append({
                'etf': etf,
                'correlated_stocks': confirmed_stocks,
                'combined_weight': round(confirmed_weight, 3)
            })
    return pd.DataFrame(flagged_pairs)
        

def optimize_w_risk_filter(train_data, loop_number=5):    
    # Iteratively optimize Sharpe, then check for factor concentration with the filter.
    # If flagged, add group-weight constraints and re-optimize. Repeat until clean. 
    bounds = [(0, 0.15) for _ in range(len(stocks))] 
    combined_weight_thresh = 0.40
    hist_returns_array = (train_data[stocks].mean() * 252).values
    cov_matrix_stocks_array = (train_data[stocks].cov() * 252).values

    # recompute corr_grid and corr_matrix for THIS training window
    train_corr_grid = pd.DataFrame(index=stocks, columns=etfs, dtype=float)
    for stock in stocks:
        for etf in etfs:
            train_corr_grid.loc[stock, etf] = train_data[stock].corr(train_data[etf])
    train_corr_matrix = train_data[stocks].corr()

    constraints = [{'type': 'eq', 'fun': lambda w: np.sum(w) - 1}]

    for i in range(loop_number):

        result = minimize(
            calc_sharpe_ratio,
            initial_weights,
            args=(cov_matrix_stocks_array, hist_returns_array, rf), 
            method='SLSQP',
            bounds= bounds,                           
            constraints = constraints
        )
        current_weights = pd.Series(result.x,  index=stocks)

        flagged_stocks = multi_risk_filter(train_corr_grid, train_corr_matrix, current_weights)
        
        if flagged_stocks.empty:
            return current_weights
        
        for _, row in flagged_stocks.iterrows():
            problem = row['correlated_stocks']
            total = current_weights[problem].sum()
            constraints.append({
            'type': 'ineq',
            'fun': lambda w, group=problem: combined_weight_thresh - pd.Series(w, index=stocks)[group].sum()
        })
    return current_weights



# covariance matrixes
ui = gen_cov_stocks(stock_data)
cov_matrix_stocks = pd.DataFrame(ui, index = stock_data.columns, columns = stock_data.columns)
up = gen_cov_stocks(data)
cov_matrix_all = pd.DataFrame(up, index = data.columns, columns = data.columns)

# correlation matrix for interpretability
corr_matrix = stock_data.corr()

# factor analysis to better identify hidden concentrations 
corr_grid = factor_analysis_corr(data)
print(corr_grid)
beta_grid = factor_analysis_beta(data)

# table demonstrating dominant ETF per stock
summary = pd.DataFrame(index=stocks)
summary['Dominant ETF'] = corr_grid.idxmax(axis=1)
summary['Correlation'] = corr_grid.max(axis=1).round(2)
summary['Beta to Dominant ETF'] = [beta_grid.loc[s, corr_grid.loc[s].idxmax()] for s in stocks]
summary['Beta to Dominant ETF'] = summary['Beta to Dominant ETF'].round(2)

# minimize to find the sharpe ratio
bounds = [(0, 0.15) for _ in range(len(stocks))] 

hist_returns_array = get_hist_returns(data).values
cov_matrix_stocks_array = cov_matrix_stocks.values


result = minimize(
    calc_sharpe_ratio,
    initial_weights,
    args=(cov_matrix_stocks_array, hist_returns_array, rf), 
    method='SLSQP',
    bounds= bounds,                            # 0 and 0.15 are my chosen bounds (ie no more than 15% into one stock)
    constraints = [{'type': 'eq', 'fun': lambda w: np.sum(w) - 1}]    #weights gotta sum to 1, each weights > 0 (no shorting)
)


#Optimized Weights 
resulting_weights = pd.Series(result.x,  index=stocks)
print("\nInitial weights with no risk filter applied:")

print(resulting_weights)

#optimized in order to avoid bunched sector risk (reweighed to algorithmically not have too much of one sector of stock in order to smooth risk)
final_weights = optimize_w_risk_filter(data)
print("\nFinal weights with risk filter applied:")
print(final_weights.round(3))


sharpe_unfiltered = -calc_sharpe_ratio(
    resulting_weights.values, 
    cov_matrix_stocks_array, 
    hist_returns_array, 
    rf
)

# Sharpe after filter
sharpe_filtered = -calc_sharpe_ratio(
    final_weights.values,
    cov_matrix_stocks_array,
    hist_returns_array,
    rf
)
## 
print(f"\nSharpe (no filter):    {sharpe_unfiltered:.3f}")
print(f"Sharpe (with filter):  {sharpe_filtered:.3f}")
print(f"Sharpe cost of filter: {sharpe_unfiltered - sharpe_filtered:.3f}")


#  MULTIPLE OUT-OF-SAMPLE BACKTESTS 
# Run the same backtest across multiple train/test splits.
# This tests whether the filter's outperformance is consistent or regime-dependent.

split_dates = ['2023-01-01', '2023-07-01', '2024-01-01', '2024-07-01']

results = []

for split_date in split_dates:
    train_data = data[data.index < split_date]
    test_data = data[data.index >= split_date]
    
    # Skip if not enough train or test data
    if len(train_data) < 252 or len(test_data) < 60:
        continue
    
    # Re-optimize on training window
    train_hist_returns = (train_data[stocks].mean() * 252).values
    train_cov = (train_data[stocks].cov() * 252).values
    bs = [(0, 0.15) for _ in range(len(stocks))]
    
    # Unfiltered
    res_u = minimize(
        calc_sharpe_ratio, initial_weights,
        args=(train_cov, train_hist_returns, rf),
        method='SLSQP', bounds=bs,
        constraints=[{'type': 'eq', 'fun': lambda w: np.sum(w) - 1}]
    )
    unf_weights = pd.Series(res_u.x, index=stocks)
    
    # Filtered
    fil_weights = optimize_w_risk_filter(train_data)
    
    # Apply to test data
    r_unf = test_data[stocks] @ unf_weights.values
    r_fil = test_data[stocks] @ fil_weights.values
    r_spy = test_data['SPY']
    r_1n = test_data[stocks].mean(axis=1)
    
    def sharpe(daily, rf_annual=0.045):
        ann_ret = daily.mean() * 252
        ann_vol = daily.std() * np.sqrt(252)
        return (ann_ret - rf_annual) / ann_vol
    
    results.append({
        'split': split_date,
        'test_days': len(test_data),
        'unfiltered': round(sharpe(r_unf), 3),
        'filtered': round(sharpe(r_fil), 3),
        'spy': round(sharpe(r_spy), 3),
        '1/N': round(sharpe(r_1n), 3),
        'filter_advantage': round(sharpe(r_fil) - sharpe(r_unf), 3)
    })

# Print results as a table
results_df = pd.DataFrame(results)

print("MULTIPLE WALK-FORWARD WINDOWS: OUT-OF-SAMPLE SHARPE BY SPLIT DATE")

print(results_df.to_string(index=False))

# Summary
print(f"\nFilter beat unfiltered in {(results_df['filter_advantage'] > 0).sum()}/{len(results_df)} windows")
print(f"Average filter advantage: {results_df['filter_advantage'].mean()} Sharpe")
print(f"Best window: {results_df['filter_advantage'].max()}")
print(f"Worst window: {results_df['filter_advantage'].min()}")